mode: pretrain_image
devices: 
  - 0

total_steps: 8000000
accumulate_grad: 3
resume: False
checkpoint: ./outputs/2022-04-03/19-00-36/checkpoint.pt
log_period: 50
batch_size: 1  # 192

model:
  _target_: models.VQBASE
  embed_dim: 256
  n_embed: 1024  # 8192
  init_steps: 2000
  ddconfig:
    z_channels: 256
    in_channels: 3
    out_channels: 3
    channels: [128, 128, 128, 256, 256, 256, 512]  # [1, 1, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions:
    - 16
    dropout: 0.0

optimizer:
  vq:
    lr: 4.5e-6
    betas:
      - 0.5
      - 0.9
  disc:
    lr: 4.5e-6
    betas:
      - 0.5
      - 0.9

dataset:
  _target_: Data.dataset_preprocessor_web.COCOWebDataset
  path: file:D:/PycharmProjects/Make-A-Scene/server/Make-A-Scene/dataset/coco/{00000..00004}.tar

loss:
  #_target_: losses.VQVAEWithBCELoss
  _target_: losses.loss_img.VQLPIPSWithDiscriminator
  disc_start: 250001
  disc_weight: 0.8
  codebook_weight: 1.0

dataloader:
  batch_size: 1
  num_workers: 8
  pin_memory: True

hydra:
  run:
    dir: ./outputs/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
