mode: preprocess_dataset
#root: "/home/ubuntu/MakeAScene/data/coco/mscoco"
root: "pipe:aws s3 cp s3://s-mas/cc12m/{00000..00621}.tar  -"
preprocessed: "/home/ubuntu/data/cc12m_tmp/"
output_folder: "cc12m_dataset"

preprocessor:
  _target_: Data.WebPreprocessor
  preprocessed_folder: ${preprocessed}
  output_folder: ${output_folder}
  batch_size: 32
  num_workers: 2
  machines_total: 1
  machine_idx: 0
  devices:
          - 9
  proc_per_gpu:
          panoptic:
                  -  4
                  -  5
                  -  6
                  -  7
          human:
                  -  2
                  -  3
          face:
                  -  0
                  -  1
  proc_per_cpu:
          panoptic: 0
          human: 0
          face: 0

dataset:
  _target_: Data.dataset_preprocessor_web.UnprocessedWebDataset
  root: ${root}

coco2014:
  _target_: Data.dataset_preprocessor.COCO2014Dataset
  root: ${root}
  preprocessed_folder: ${preprocessed}

coco2017:
  _target_: Data.dataset_preprocessor.COCO2017Dataset
  root: ${root}
  preprocessed_folder: ${preprocessed}


hydra:
  run:
    dir: ./outputs/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
